name: Update certs

on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 * * *' # Nightly 6AM UTC


permissions:
  contents: read

jobs:
  update-certs:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v.24.0


    - name: Update certs
      run: cd orbit/pkg/packaging && ./mk-ca-bundle.pl -u certs.pem

    - name: PR changes
      uses: peter-evans/create-pull-request@20dac2ed4875a1a8422d233a68f69088637446df # v3.12.1
      with:
        base: main
        branch: update-ca-certs
        delete-branch: true
        title: Update Orbit CA certs [automated]
        commit-message: |
          Update Orbit CA certs [automated]

          Generated automatically with curl mk-ca-bundle.pl script.
        body: Automated change from [GitHub action](https://github.com/fleetdm/fleet/actions/workflows/update-certs.yml).
